### ISSUE TITLE
PDF Generation encoding problems

### ISSUE THREAD

**Issue by avmaisak** [RusBit/LFS_Book#1]

**Comment by MeshAndrey** [comment]
Нашел причину проблемы. При генерации pdf используется утилита fop. Она генерирует логи:

[WARN] FOUserAgent - Font "Symbol,normal,700" not found. Substituting with "Symbol,normal,400".
[WARN] FOUserAgent - Font "ZapfDingbats,normal,700" not found. Substituting with "ZapfDingbats,normal,400".
[WARN] FOUserAgent - Glyph "В" (0x412, Vecyrillic) not available in font "Helvetica-Bold".
[WARN] FOUserAgent - Glyph "е" (0x435, afii10070) not available in font "Helvetica-Bold".
[WARN] FOUserAgent - Glyph "р" (0x440, afii10082) not available in font "Helvetica-Bold".
[WARN] FOUserAgent - Glyph "с" (0x441, afii10083) not available in font "Helvetica-Bold".
[WARN] FOUserAgent - Glyph "и" (0x438, afii10074) not available in font "Helvetica-Bold".
[WARN] FOUserAgent - Glyph "я" (0x44f, afii10097) not available in font "Helvetica-Bold".
[WARN] FOUserAgent - Glyph "С" (0x421, Escyrillic) not available in font "Helvetica-Bold".
[WARN] FOUserAgent - Glyph "о" (0x43e, afii10080) not available in font "Helvetica-Bold".

и т.д.
Судя по документации,
Every font contains a particular set of glyphs. If no glyph can be found for a given character, FOP will issue a warning and use the glpyh for "#" (if available) instead. 
Т.е. проблема в шрифтах. В документации рекомендуют использовать другие шрифты, пока неясно как заменить их.

**Comment by MeshAndrey** [comment]
Смог решить частично проблему. Заменил, какие смог, шрифты на свои, однако есть проблема с дефолтными.
[output.pdf](https://github.com/avmaisak/LFS_Book/files/4476066/output.pdf)

**Comment by avmaisak** [comment]
@MeshAndrey  - где происходит замена шрифтов?

**Comment by MeshAndrey** [comment]
я отдельно создал конфиг файл и скачал шрифты с поддеркой utf-кодировки. а потом:
andrey@desktop:~/tmp$ fop -q  lfs-pdf.fo -c config.xml output.pdf 2>fop.log
где config.xml конфиг-файл

**Comment by MeshAndrey** [comment]
1) скачать и разархивировать шрифты в папку /home/user_name/.fonts. если её нет - создать. она будет невидимой, поэтому нужно либо в диспетчере файлов поставить "показывать скрытые файлы/папки" или использовать ls -a.
[cmu-serif.zip](https://github.com/avmaisak/LFS_Book/files/4476167/cmu-serif.zip)
2) перейти в директорию с книгой, $ make pdf
3) перейти в папку /home/username/tmp
4) создать файл конфигурации config.xml и подкрутить под себя пути
[config.zip](https://github.com/avmaisak/LFS_Book/files/4476257/config.zip)
5) запустить fop в этой же папке: $ fop -q  lfs-pdf.fo -c config.xml output.pdf 2>fop.log
6) output.pdf - собранный файл, fop.log - логи

**Comment by MeshAndrey** [comment]
смог полностью пофиксить проблему. 
[output.pdf](https://github.com/avmaisak/LFS_Book/files/4558955/output.pdf)
чуть позже сделаю скрипты отправлю пулл реквест.

**Comment by avmaisak** [comment]
Спасибо за помощь! Жду PR

**Comment by MeshAndrey** [comment]
от ещё вариант 
[output.pdf](https://github.com/avmaisak/LFS_Book/files/4559381/output.pdf)
(тут другие шрифты, вроде и отображаются лучше), но возможна проблема с:
[WARN] FOUserAgent - Glyph "‐" (0x2010, hyphentwo) not available in font "OpenSans-Regular".
на всю книгу пока что только 2 места где это произошло, и, вроде, не критично. только вот что в других версиях потом будет хз.
также есть немного проблемы с центрированием (кириллица чуть ниже латины),
![screen7](https://user-images.githubusercontent.com/35770825/80732314-d0fbef80-8b14-11ea-971d-fe744ba64bad.jpg)

 но тут уже не знаю, что делать, это проблема уже или шрифта, или самой утилиты. Та же проблема в предыдущем файле, только там она более заметная. Какой вариант взять финальным?

**Comment by avmaisak** [comment]
@MeshAndrey второй вариант вроде как получше.
