### ISSUE TITLE
Frequently Asked Questions

### ISSUE THREAD

**Issue by avmaisak** [RusBit/LFS_Book#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by F48D1** [comment]
I can't do XML to PDF.
Make error:
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
Document /home/fr3nd/tmp/lfs-html2.xml does not validate
make: *** [Makefile:138: validate] Error 3

**Comment by ghost** [comment]
I can't do XML to PDF.
Make error:
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
Document /home/fr3nd/tmp/lfs-html2.xml does not validate
make: *** [Makefile:138: validate] Error 3

**Comment by avmaisak** [comment]
what OS did you use?
For properly build see https://github.com/avmaisak/LFS_Book/blob/master/INSTALL file.
