### ISSUE TITLE
README и Markdown

### ISSUE THREAD

**Issue by lfs-ru** [RusBit/LFS_Book#22]
Возможно, стоит переименовать `README` в `README.md` и внести небольшие стилистические правки? Это даёт возможность слегка украсить описание проекта.

Может и не стоит - не знаю, как у вас задумано :)

**Comment by avmaisak** [comment]
Вопрос хороший. Текущий файл README взят из оригинального репозитория SVN. Можно создать дополнительный файл README.md и внести в него необходимую информацию, а обычный README - оставить как есть.
