### ISSUE TITLE
Ошибка отображения кириллицы в PDF файлах версий 8.*

### ISSUE THREAD

**Issue by AKonia** [RusBit/LFS_Book#34]
При скачивании с сайта https://book.linuxfromscratch.ru/ версии 8.*(9.0-dev в порядке) в переводе вся кириллица отрисована решётками(#) 
![Снимок экрана_2021-03-08_17-57-28](https://user-images.githubusercontent.com/7058335/110338303-e6488100-8037-11eb-80f5-b84c63fdd695.png)
![Снимок экрана_2021-03-08_17-57-45](https://user-images.githubusercontent.com/7058335/110338315-e8aadb00-8037-11eb-9a5d-c013052c155e.png)

**Comment by avmaisak** [comment]
wontfix
